### ISSUE TITLE
jpeg2pattern return?

### ISSUE THREAD

**Issue by zilong** [postgrespro/imgsmlr#3]
SQL: **SELECT 
            id, 
            jpeg2pattern(image_data) AS pattern 
        FROM  images where id = 11111;**  

but pattern return null？some image is no support?
the image URL: https://cbu01.alicdn.com/img/ibank/2016/724/363/2764363427_8489247.jpg

**Comment by akorotkov** [comment]
Hi!

This file appears to be gif with jpeg extension.
```
$ file 2764363427_8489247.jpg
2764363427_8489247.jpg: GIF image data, version 89a, 800 x 800
```
gif2pattern() works fine with that file.  Image format autodetection is not yet supported.
